### ISSUE TITLE
i use ctrl+v once to copy a string into TextField,but he did it twice

### ISSUE THREAD

**Issue by geata** [go-flutter-desktop/go-flutter#320] opened 2019-12-01 16:05 UTC
"a" is in my clipboard,where i use ctrl+v once,i got "aa"

**Comment by pchampio** [comment] 2019-12-01 16:18
Duplicate of #314  
Please read: https://github.com/go-flutter-desktop/go-flutter/issues/319#issuecomment-558557949

**Closed by pchampio** 2019-12-01 16:18 UTC
