### ISSUE TITLE
hover packaging is error prone

### ISSUE THREAD

**Issue by james-lawrence** [go-flutter-desktop/go-flutter#428] opened 2020-05-07 21:12 UTC
## Hover doctor
```
hover doctor
hover: Hover version v0.41.4 running on linux
hover: Sharing flutter version
Flutter 1.17.0 • channel beta • ssh://git@github.com/flutter/flutter.git
Framework • revision e6b34c2b5c (5 days ago) • 2020-05-02 11:39:18 -0700
Engine • revision 540786dd51
Tools • Dart 2.8.1
hover: Flutter engine commit: https://github.com/flutter/engine/commit/540786dd51f112885a89792d678296b95e6622e5
hover: Finding out the C compiler version
gcc (Arch Linux 9.3.0-1) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

hover: Sharing the content of go.mod
module gitlab.com/james-lawrence/egab

require (
	github.com/go-flutter-desktop/go-flutter v0.40.1
	github.com/go-flutter-desktop/hover v0.41.4 // indirect
	github.com/go-flutter-desktop/plugins/image_picker v0.1.5
	github.com/pkg/errors v0.9.1
)

go 1.14
hover: Sharing the content of hover.yaml
application-name: ""
executable-name: ""
package-name: ""
license: ""
target: lib/main.dart
branch: '@v0.40.1'
cache-path: ""
opengl: ""
engine-version: ""
hover: Sharing the content of go/cmd
go/cmd/import-image_picker-plugin.go	go/cmd/main.go	go/cmd/options.go

```

## Error output
```
hover build --debug darwin-dmg
hover: Cleaning the build directory
hover: Building flutter bundle
hover: Using engine from cache
hover: Downloading 'go-flutter' @v0.40.1
go: github.com/pkg/errors upgrade => v0.9.1
go: golang.org/x/text upgrade => v0.3.2
# github.com/go-flutter-desktop/go-flutter/embedder
/usr/bin/ld: cannot find -lflutter_engine
collect2: error: ld returned 1 exit status
hover: Updating go-flutter to @v0.40.1 version failed: exit status 2
```
```
hover build --debug --docker darwin-dmg
hover: Cleaning the build directory
hover: Building flutter bundle
hover: Using engine from cache
hover: Compiling go binary using docker container
Running this docker command: /usr/bin/docker run --rm --mount type=bind,source=/shared/james-lawrence/development/egab/console,target=/app --mount type=bind,source=/shared/james-lawrence/.cache/hover/engine,target=/root/.cache/hover/engine --mount type=bind,source=/shared/james-lawrence/.cache/hover/docker-go-cache,target=/go-cache --env GOCACHE=/go-cache --env HOVER_SAFE_CHOWN_UID=1000 --env HOVER_SAFE_CHOWN_GID=1000 --env GOPROXY=direct
 --env GOPRIVATE=
 goflutter/hover:v0.41.4 hover-safe.sh build darwin-dmg --target lib/main.dart --skip-flutter-build-bundle --skip-engine-download --debug
docker container: hover: Downloading 'go-flutter' @v0.40.1
docker container: go: finding github.com/go-flutter-desktop/go-flutter v0.40.1
docker container: go: downloading github.com/go-flutter-desktop/go-flutter v0.40.1
docker container: go: extracting github.com/go-flutter-desktop/go-flutter v0.40.1
docker container: go: downloading github.com/Xuanwo/go-locale v0.2.0
docker container: go: downloading golang.org/x/text v0.3.2
docker container: go: downloading github.com/go-gl/gl v0.0.0-20190320180904-bf2b1f2f34d7
docker container: go: downloading github.com/go-gl/glfw/v3.3/glfw v0.0.0-20200420212212-258d9bec320e
docker container: go: extracting github.com/go-gl/glfw/v3.3/glfw v0.0.0-20200420212212-258d9bec320e
docker container: go: extracting github.com/Xuanwo/go-locale v0.2.0
docker container: go: downloading github.com/go-ole/go-ole v1.2.4
docker container: go: extracting github.com/go-ole/go-ole v1.2.4
docker container: go: extracting github.com/go-gl/gl v0.0.0-20190320180904-bf2b1f2f34d7
docker container: go: extracting golang.org/x/text v0.3.2
docker container: go: finding github.com/go-gl/glfw/v3.3/glfw latest
docker container: go: finding github.com/Xuanwo/go-locale v0.2.0
docker container: go: finding github.com/go-gl/gl latest
docker container: go: finding github.com/go-ole/go-ole v1.2.4
docker container: go: finding golang.org/x/text v0.3.2
docker container: # github.com/go-flutter-desktop/go-flutter/embedder
docker container: /usr/bin/ld: cannot find -lflutter_engine
docker container: collect2: error: ld returned 1 exit status
docker container: hover: Updating go-flutter to @v0.40.1 version failed: exit status 2
hover: Docker run failed: exit status 1
```

**Comment by pchampio** [comment] 2020-05-25 16:38
Duplicate of #413 

hover will always download go-flutter if the `branch` field is set in hover.yaml. We have to perform this to keep `@latest` of `@master` always update. Always downloading is the default behavior.

As you are using a tagged version of go-flutter, you don't need to explicitly ask for the `'@v0.40.1'` branch. Please leave it empty.

Everything else is detailed in: https://github.com/go-flutter-desktop/go-flutter/issues/413#issuecomment-633641403

Should be fixed in: https://github.com/go-flutter-desktop/hover/pull/142

**Comment by pchampio** [comment] 2020-05-25 17:18
We plan to remove the `branch` field from hover.yaml.
go-flutter version is tracked with go/go.mod.

The `-b` flag on hover will also be hidden.

**Closed by pchampio** 2020-05-25 17:18 UTC
Labels: duplicate, hover
