### ISSUE TITLE
TextField value copied to another TextField when lost focus on Windows.

### ISSUE THREAD

**Issue by ekasetiawans** [go-flutter-desktop/go-flutter#246] opened 2019-09-04 11:32 UTC
Let's say, I have 2 TextFields in a page, when I type something in first TextField then I focus to second TextField, the text I have type on first TextField is copied into second TextField.

this happen on windows only, I try on linux the application is running normaly.
this issue is solved when I use beta branch yesterday. Now, beta branch is gone.

Sorry for bad english.

**Comment by Drakirus** [comment] 2019-09-04 12:56
Beta had been merged to master.
Could you update to the latest version of hover and run `hover update`

**Comment by ekasetiawans** [comment] 2019-09-05 10:24
I have try `hover update` but not resolved

**Comment by Drakirus** [comment] 2019-09-05 10:36
can you share a reproducible example?

**Comment by ekasetiawans** [comment] 2019-09-05 11:35
https://drive.google.com/open?id=1i0otAA0rcfKw4OTZ7Ws8H4tSf_vwwUlc

**Comment by Drakirus** [comment] 2019-09-05 13:27
related (but not duplicate) of https://github.com/go-flutter-desktop/go-flutter/issues/221

It's a flutter issue, dirty workaround:
```
                onEditingComplete: () {
                  FocusScope.of(context).requestFocus(_txtPasswordNode);
                  WidgetsBinding.instance.addPostFrameCallback((_) {
                    _txtPassword.clear();
                    _txtPassword.selection =
                        TextSelection(baseOffset: 0, extentOffset: 0);
                  });
                },
```

**Comment by Drakirus** [comment] 2019-09-05 13:29
Please look on the flutter issue tracker if there are related issues.
Some similar (but not same):
https://github.com/flutter/flutter/issues/35848
https://github.com/flutter/flutter/issues/20016
https://github.com/flutter/flutter/issues/7247

**Comment by ekasetiawans** [comment] 2019-09-05 23:53
I feel it's a little weird, because in the previous beta branch it didn't happen.  Before the beta branch was merged with the master branch, I compared it using the same source code and the same flutter version, but the issue only occurred in the master branch.

**Comment by nalaws** [comment] 2019-09-06 01:05
修改 text_field.dart文件中函数 void handleSingleTapUp(TapUpDetails details) . 里的代码

    _renderEditable.selectPosition(cause: SelectionChangedCause.tap);

为

    if(widget.focusNode != null) {
    _renderEditable.selectPosition(cause: SelectionChangedCause.tap);
    }

**Comment by Drakirus** [comment] 2019-09-06 15:26
> I feel it's a little weird, because in the previous beta branch it didn't happen. Before the beta branch was merged with the master branch, I compared it using the same source code and the same flutter version, but the issue only occurred in the master branch.

Well you see, it's even weirder for us, we try to stay compliant with the flutter framework, but sometimes bugs occurs and we don't really know how to react.  
In #221 I've added code to handle invalid selection base/extent values, this fix isn't behaving the same way as it used to be due to Flutter updates. 

I'm working on a fix that complies with the Android error behavior. (Yes this error occurs on others platforms)

**Closed** 2019-09-06 15:27 UTC
Labels: embedder, enhancement, warning

**Comment by Drakirus** [comment] 2019-09-06 15:29
This warning was originally reported from the https://github.com/fluttercandies/JsonToDart/tree/master/Flutter/desktop project.
I've tested JsonToDart, it works the same as it used to be.

**Comment by Drakirus** [comment] 2019-09-06 15:29
tagged into `v0.29.1`
