### ISSUE TITLE
Can't pass --track-widget-creation with hover run, is there another way? 

### ISSUE THREAD

**Issue by MostHated** [go-flutter-desktop/go-flutter#216] opened 2019-08-02 01:16 UTC
Hey there,
   I was trying to check some things in devtools but it said I needed --track-widget-creation enabled, so I tried including it using ```hover run --track-widget-creation``` but then I end up with an unknown flag error. Is there another way to enable it that I am not seeing? I looked through the h menu in the console but none of them jumped out as something comparable. I checked through what I could see in the available debug methods to enable similar to ```debugDefaultTargetPlatformOverride``` but I didn't see anything there that looked like it either.

Is this something that can be enabled somehow?

Side question, is it possible yet to attach to Android Studio to allow the debugger to work? I see there was a way you can manually enter a remote address, but it doesn't let you modify it the way it would need to be to accept the uri that is output in the console. It keeps trying to use ws://localhost/c9g_XXpYOHI=/:50300/ws but you can't seem to modify it that I can tell.

Thanks,
-MH

**Comment by Drakirus** [comment] 2019-08-02 08:01
Whenever you have request on hover, please check the latest version of hover. 
Updating hover to the latest version will fix your issue. https://github.com/go-flutter-desktop/hover/commit/b38033fe91baf13046e2a7788859e6b58f4284c6 .
The `--track-widget-creation` flag is set by default when running `hover run`.

**Comment by Drakirus** [comment] 2019-08-02 08:03
For the side question:
>  is it possible yet to attach to Android Studio to allow the debugger to work?
It's a duplicate of: https://github.com/go-flutter-desktop/go-flutter/issues/213

**Closed** 2019-08-02 08:02 UTC
