### ISSUE TITLE
issue with "hover build windows" command 

### ISSUE THREAD

**Issue by ibrahem777** [go-flutter-desktop/go-flutter#280] opened 2019-10-12 10:30 UTC
Flutter 1.9.1+hotfix.2 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 2d2a1ffec9 (5 weeks ago) • 2019-09-06 18:39:49 -0700
Engine • revision b863200c37
Tools • Dart 2.5.0

when i run "hover build windows" command
this issue appears 
"
C:\examples-master\draggable_borderless>hover build windows
[1;36mhover: [0mUsing engine from cache
[1;36mhover: [0mCleaning the build directory
[1;36mhover: [0m[32mBundling flutter app[0m
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
hover: Flutter build failed: exit status 1"

can you please help me to fix this issue

**Comment by Drakirus** [comment] 2019-10-12 10:53
Can you share the result of  `flutter build bundle` where you have run the above hover command?

**Comment by Drakirus** [comment] 2019-10-12 10:57
*Putting this here, not sure if it's the cause of the issue or not.*

I recommend using a different terminal than the windows cmd. 
https://github.com/cmderdev/cmder/releases/download/v1.3.12/cmder_mini.zip
 does a great job.

**Comment by pchampio** [comment] 2019-11-03 23:17
Without additional information, we are unfortunately not sure how to resolve
this issue. We are therefore reluctantly going to close this bug for now. Please
don't hesitate to comment on the bug if you have any more information for us; we
will reopen it right away!
Thanks for your contribution.

**Closed by pchampio** 2019-11-03 23:17 UTC
Labels: Windows, needs info
