### ISSUE TITLE
Can not show Chinese?

### ISSUE THREAD

**Issue by jinfagang** [go-flutter-desktop/go-flutter#454] opened 2020-05-30 02:41 UTC
I using go-flutter migrate my App to desktop very nicely.

But  main issue is:

- Chinese charactors can not shown;

![image](https://user-images.githubusercontent.com/21303438/83317785-e8d4a980-a261-11ea-8985-35dfd1774a11.png)

**Comment by GeertJohan** [comment] 2020-05-30 08:56
You are probably using a font that is not available on your machine, or the version on your machine does not include chinese glyphs. Make sure to include any font that you want to use in the your assets list in pubspec.yaml.

**Comment by jinfagang** [comment] 2020-05-30 15:18
maybe just default one?no custom fonts, also i am on linux and my ubuntu shows CHINESE correct

**Comment by pchampio** [comment] 2020-05-30 18:27
Duplicate of:
https://github.com/go-flutter-desktop/go-flutter/issues/223
https://github.com/go-flutter-desktop/go-flutter/issues/80

**Closed by pchampio** 2020-05-30 18:27 UTC
