### ISSUE TITLE
Texture support

### ISSUE THREAD

**Issue by gedw99** [go-flutter-desktop/go-flutter#130] opened 2019-05-04 20:22 UTC
It looks like we finally got texture support.
https://github.com/google/flutter-desktop-embedding/issues/107

**Comment by Drakirus** [comment] 2019-05-04 21:03
Duplicate of #102

**Comment by Drakirus** [comment] 2019-05-04 21:05
For those kinds of 'issues' use the gitter chat. Thanks

**Closed by Drakirus** 2019-05-04 21:05 UTC
