### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by xinglinsky** [go-flutter-desktop/go-flutter#473] opened 2020-06-15 08:27 UTC
win10 x64：
E:\Project\flutter\demo1  
λ go version
go version go1.14.3 windows/amd64

E:\Project\flutter\demo1  
λ hover run
?[1;36mhover: ?[0m?[33m⚠ The go-flutter project tries to stay compatible with the beta channel of Flutter.?[0m
?[1;36mhover: ?[0m?[33m⚠     It's advised to use the beta channel: `?[35mflutter channel beta?[0m`?[0m
?[1;36mhover: ?[0m?[32mBuilding flutter bundle?[0m
hover: Using engine from cache
hover: Checking available release on Github
hover: Cannot obtain version information from hover build. To resolve this, please go-get hover using Go 1.13 or newer.

**Comment by jld3103** [comment] 2020-06-15 10:47
Duplicate of https://github.com/go-flutter-desktop/go-flutter/issues/471

**Closed by jld3103** 2020-06-15 10:47 UTC
