### ISSUE TITLE
Cannot obtain version information from hover build. To resolve this, please go-get hover using Go 1.13 or newer.

### ISSUE THREAD

**Issue by YourksChan** [go-flutter-desktop/go-flutter#483] opened 2020-06-30 04:07 UTC
cached_network_image: ^2.2.0+1
  shared_preferences: ^0.5.7+3
  spreadsheet_decoder: ^1.1.0
  cupertino_icons: ^0.1.3
  pull_to_refresh: ^1.6.0
  progress_dialog: ^1.2.4
  url_launcher: ^5.4.11
  common_utils: ^1.2.1
  file_picker: ^1.12.0
  flutter_svg: ^0.17.4
  fish_redux: ^0.3.4
  encrypt: ^4.0.2
  fluro: ^1.6.3
  toast: ^0.1.5
  intl: ^0.16.1
  dio: ^3.0.9

Flutter 1.17.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b041144f83 (4 weeks ago) • 2020-06-04 09:26:11 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4

'go-flutter' is on version: v0.41.1

go version
go version go1.14.4 darwin/amd64

hover doctor
hover: Cannot obtain version information from hover build. To resolve this, please go-get hover using Go 1.13 or newer.

**Comment by pchampio** [comment] 2020-06-30 08:01
Duplicate of https://github.com/go-flutter-desktop/go-flutter/issues/471

**Comment by SureshKumar311** [comment] 2020-09-21 08:58
try this 

go env GO111MODULE =on

go get -u -a github.com/go-flutter-desktop/hover

i had tryed for me working

C:\Users\sk>go env GO111MODULE =on
on


C:\Users\sk>GO111MODULE=on go get -u -a github.com/go-flutter-desktop/hover
'GO111MODULE' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\sk>go get -u -a github.com/go-flutter-desktop/hover
go: downloading github.com/go-flutter-desktop/hover v0.43.0
go: github.com/go-flutter-desktop/hover upgrade => v0.43.0
go: downloading golang.org/x/mod v0.3.0
go: downloading github.com/GeertJohan/go.rice v1.0.0
go: downloading github.com/hashicorp/go-version v1.2.1
go: downloading github.com/Kodeworks/golang-image-ico v0.0.0-20141118225523-73f0f4cfade9
go: downloading github.com/daaku/go.zipexe v1.0.1
go: downloading github.com/tcnksm/go-latest v0.0.0-20170313132115-e3007ae9052e
go: downloading golang.org/x/xerrors v0.0.0-20191011141410-1b5146add898
go: downloading golang.org/x/net v0.0.0-20200324143707-d3edc9973b7e
go: downloading github.com/google/go-github v17.0.0+incompatible
go: downloading github.com/otiai10/copy v1.2.0
go: downloading github.com/google/go-querystring v1.0.0
go: github.com/spf13/pflag upgrade => v1.0.5
go: gopkg.in/yaml.v2 upgrade => v2.3.0
go: github.com/pkg/errors upgrade => v0.9.1
go: github.com/daaku/go.zipexe upgrade => v1.0.1
go: golang.org/x/xerrors upgrade => v0.0.0-20200804184101-5ec99f83aff1
go: golang.org/x/net upgrade => v0.0.0-20200904194848-62affa334b73
go: golang.org/x/sys upgrade => v0.0.0-20200918174421-af09f7315aff
go: downloading golang.org/x/net v0.0.0-20200904194848-62affa334b73
go: downloading golang.org/x/xerrors v0.0.0-20200804184101-5ec99f83aff1
go: downloading golang.org/x/sys v0.0.0-20200918174421-af09f7315aff

C:\Users\sk>hover
Hover helps developers to release Flutter applications on desktop.

Usage:
  hover [command]

Available Commands:
  build          Build a desktop release
  bumpversion    upgrade the 'go-flutter' golang library in this project
  doctor         Show information about the installed tooling
  help           Help about any command
  init           Initialize a flutter project to use go-flutter
  init-packaging Create configuration files for a packaging format
  init-plugin    Initialize a go-flutter plugin in a existing flutter platform plugin
  plugins        Tools for plugins
  publish-plugin Publish your go-flutter plugin as golang module in your github repo.
  run            Build and start a desktop release, with hot-reload support
  version        Print Hover version information

Flags:
      --colors    Add colors to log (default true)
      --docker    Run the command in a docker container for hover
  -h, --help      help for hover
  -v, --verbose   increase logging verbosity

Use "hover [command] --help" for more information about a command.

C:\Users\sk>hover version
Hover v0.43.0

**Closed** 2020-11-01 20:04 UTC
