### ISSUE TITLE
hover: uses wrong LDflags when fetching dependencies during builds.

### ISSUE THREAD

**Issue by james-lawrence** [go-flutter-desktop/go-flutter#429] opened 2020-05-07 22:29 UTC
when building darwin-dmg on linux using `hover build --cache-path=/tmp darwin-dmg`

it attempts to update go-flutter using the darwin flags flags which confuses the go build command because its running in a linux environment.
[offending code](https://github.com/go-flutter-desktop/hover/blob/master/cmd/bumpversion.go#L58)

this results in the following situation in go-flutter#build.go:
```bash
# cgo ldflags environment specified by hover CGO_LDFLAGS=-F/tmp/hover/engine/darwin -Wl,-rpath,@executable_path
```
```golang
// build.go golang tooling attempts to load the flutter_engine.so file from /tmp/hover/engine/darwin
// because it detects the linux environment.

// #cgo linux LDFLAGS: -lflutter_engine -Wl,-rpath,$ORIGIN
// #cgo windows LDFLAGS: -lflutter_engine
// #cgo darwin LDFLAGS: -framework FlutterEmbedder
import "C"
```

this results in the following error:
```
# github.com/go-flutter-desktop/go-flutter/embedder
/usr/bin/ld: cannot find -lflutter_engine
collect2: error: ld returned 1 exit status
hover: Updating go-flutter to @v0.40.1 version failed: exit status 2
```

specifying GOOS=darwin causes other issues:

```
GOOS=darwin hover build --cache-path=/tmp darwin-dmg
../../../../go/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.40.1/event-loop.go:10:2: build constraints exclude all Go files in /shared/james-lawrence/go/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.40.1/internal/currentthread
../../../../go/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.40.1/internal/opengl/opengl.go:12:2: build constraints exclude all Go files in /shared/james-lawrence/go/pkg/mod/github.com/go-gl/gl@v0.0.0-20190320180904-bf2b1f2f34d7/v3.3-core/gl
../../../../go/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.40.1/internal/opengl/opengl.go:13:2: build constraints exclude all Go files in /shared/james-lawrence/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200420212212-258d9bec320e
```

**Comment by pchampio** [comment] 2020-05-08 13:26
Can you try with: `go get -u -d github.com/go-flutter-desktop/go-flutter`  

Use the `-d` flag in https://github.com/go-flutter-desktop/hover/blob/master/cmd/bumpversion.go#L74.


As for `GOOS`, it is be because you aren't on `darwin` (from past discussion I think you are on linux), and the C compiler are simply not available resulting in failure to compile embedded C code in the listed package.
Cf: https://github.com/go-flutter-desktop/hover/blob/74bbb5fc06881e3e07c10aa0cdfc180df5bbcfdc/cmd/build.go#L460-L471

**Comment by pchampio** [comment] 2020-05-08 13:28
FYI, thanks for reporting the error, I'm kinda in a rush, and should really not be there at the moment.
I've crafted my response in a hurry.

**Comment by pchampio** [comment] 2020-05-08 13:45
> it attempts to update go-flutter using the darwin flags flags which confuses the go build command because its running in a linux environment.

Mhumm, are we sure https://github.com/go-flutter-desktop/hover/blob/master/cmd/bumpversion.go#L74 is executed when running `hover build --cache-path=/tmp darwin-dmg` that very surprising.

**Comment by pchampio** [comment] 2020-05-25 16:28
Duplicate of #413 

Please read: https://github.com/go-flutter-desktop/go-flutter/issues/413#issuecomment-633641403

Should be fixed in: https://github.com/go-flutter-desktop/hover/pull/142

**Closed by pchampio** 2020-05-25 16:28 UTC
Labels: hover
