### ISSUE TITLE
crash in osx10.14.5  when resize main window

### ISSUE THREAD

**Issue by nowind** [go-flutter-desktop/go-flutter#228] opened 2019-08-09 08:25 UTC
Following the guideline,i run "hover run" in examples project / pointer_demo ,the main window opened,but carsh happens when i resize the window with following massage:
hover: app 'pointer_demo' exited with error: signal: segmentation fault

**Comment by zephylac** [comment] 2019-08-09 09:21
Could you post more info about your error ?

I'm currently using MacOS 10.14.6 and I'm not having any issue when resizing. Maybe if you update your OS it won't happen again

**Comment by Drakirus** [comment] 2019-08-09 10:40
This is a longstanding issue of the Flutter Engine. 
Duplicate of https://github.com/go-flutter-desktop/go-flutter/issues/133

**Closed by Drakirus** 2019-08-09 10:40 UTC
