### ISSUE TITLE
AppImage: .DirIcon is missing

### ISSUE THREAD

**Issue by marchellodev** [go-flutter-desktop/go-flutter#409] opened 2020-04-23 15:56 UTC
When trying to submit AppImage to [AppImageHub](https://appimage.github.io), I am having this error:

`FATAL: .DirIcon is missing in /tmp/.mount_BeingTQfaB4a`

([link to a full log](https://travis-ci.org/github/AppImage/appimage.github.io/builds/678647679))

**Comment by jld3103** [comment] 2020-04-23 16:03
That's known. I'm not sure how to fix it, because there is a lack of documentation about that. I hope I can comeup with a solution in the next few days, but I can't promise anything

**Comment by jld3103** [comment] 2020-04-23 17:26
@marchellodev Another thing to mention: You app uses a very old hover version. You can update it (same go get command as to install) and then reinit the project `rm go && hover init`. In the latest version you can control a lot of names for like the application, executable and the package. That won't fix your problem, but it gives you a lot more features!

**Comment by marchellodev** [comment] 2020-04-23 17:28
@jld3103 is there a way to check the installed version of hover?

**Comment by jld3103** [comment] 2020-04-23 17:35
Maybe @probonopd could you explain to me how to create a correct `.DirIcon`? I understand if that's not your matter, but there is so little documentation on how to do that.

**Comment by probonopd** [comment] 2020-04-23 18:07
Simply place a png in a Linux standard icon size (e.g., 128x128px) in `.DirIcon` into the AppDir root directory. Normally tools that produce AppDirs/AppImages should do this automatically, e.g., by copying the icon specified in the desktop file `Icon=...` key there.

**Comment by jld3103** [comment] 2020-04-23 18:22
Ok thanks. I hope that works

**Comment by jld3103** [comment] 2020-04-23 18:26
@probonopd [This document](https://docs.appimage.org/reference/appdir.html) says that it needs be a symlink. That was what I tried, but I didn't get it to work. I think that document is outdated.

**Comment by jld3103** [comment] 2020-04-23 18:41
@probonopd I'm using this command: `cp build/assets/icon.png .DirIcon && appimagetool .`. I copies a png icon with the size of 256x256 to the `.DirIcon` and then builds the AppImage, but still I get this error message:
```log
WARNING: No icons found at "usr/share/icons"
WARNING: Using .DirIcon as default app icon
ERROR: Unable to load image.
ERROR: No icon was generated for: /home/jld3103/Applications/gofluttertest-1.0.0+1_9ddc72cafd2a928b3f181bb797aac3bd.AppImage
Segmentation fault (core dumped)
```

**Comment by probonopd** [comment] 2020-04-23 19:30
please also copy the icon to `usr/share/icons/hicolor/256x256/apps/flutter.png` if your desktop file has `Icon=flutter`. Which tool are you using that is saying "ERROR: Unable to load image."?

**Comment by jld3103** [comment] 2020-04-23 19:32
Just launching the AppImage from the command line and then clicking on integrate and run. I guess that means it's running using appimaged?

**Comment by probonopd** [comment] 2020-04-23 19:35
Sounds a lot like https://github.com/TheAssassin/AppImageLauncher. cc @TheAssassin

**Comment by probonopd** [comment] 2020-04-23 19:36
> @probonopd This document says that it needs be a symlink.

Changed, as I could not find anything in the ROX AppDir description that would indicate it needs to be a symlink.

**Comment by jld3103** [comment] 2020-04-23 19:55
@probonopd This is the full application with the correct icon layout (now files but also tried with symlinks, but got the same result).
Now an icon is shown on the file and running once still works, but when trying to integrate it it fails with `Segmentation fault (core dumped)`. Nothing more. I guess then it's not an appimage error rather than an appimagelauncher error, right?

[hover-build-go_flutter_test-linux-appimage277435954.tar.gz](https://github.com/go-flutter-desktop/go-flutter/files/4524872/hover-build-go_flutter_test-linux-appimage277435954.tar.gz)

**Comment by marchellodev** [comment] 2020-05-01 14:33
@probonopd @jld3103 any updates?

**Comment by jld3103** [comment] 2020-05-01 15:39
I'm not sure how to proceed or even if the error I encounter is the same that you encouter

**Comment by probonopd** [comment] 2020-05-02 07:40
@jld3103 

> hover-build-go_flutter_test-linux-appimage277435954.tar.gz

This is an AppDir, not an AppImage.

When I convert it to an AppImage like this:

```
ARCH=x86_64 VERSION=1 /isodevice/Applications/appimagetool-446-x86_64.AppImage Downloads/hover-build-go_flutter_test-linux-appimage277435954
```

the AppImage works well on Xubuntu 18.04.4 LTS, and it has the correct icon when the optional appimaged daemon is used for desktop integration both in the file manager and in the menu:

![icon](https://user-images.githubusercontent.com/2480569/80858249-c68e4280-8c47-11ea-99b0-6d7c0c46b0bb.png)

![menu](https://user-images.githubusercontent.com/2480569/80858299-1a992700-8c48-11ea-9325-40f5659ddc83.png)

So I think the AppImage is fine as it is.

**Comment by jld3103** [comment] 2020-05-02 11:12
Ok nice thanks. I'm not sure if I didn't read the documentation or if the documentation was wrong. Anyway I'm glad you helped me

**Comment by jld3103** [comment] 2020-05-02 12:33
@probonopd Now I used appimaged (also uninstalled appimagelauncher) and put the AppImage under `$HOME/Applications` and ran `appimaged`, but got this error message:
```log
appimaged, continuous build (commit b096cd3), build 221 built on 2020-03-30 19:16:46 UTC
Watching /home/jld3103/.local/bin
Watching /home/jld3103/Downloads
Watching /home/jld3103/bin
WARNING: No icons found at "usr/share/icons"
WARNING: Using .DirIcon as default app icon
Segmentation fault (core dumped)
```

**Comment by jld3103** [comment] 2020-05-02 12:36
When using the go-appimagetool I get this:
```log
appimaged, continuous build (commit b096cd3), build 221 built on 2020-03-30 19:16:46 UTC
Watching /home/jld3103/.local/bin
Watching /home/jld3103/Downloads
Watching /home/jld3103/bin
Extracting usr/share/icons/hicolor/256x256/apps/go_flutter_test.png to "/home/jld3103/.local/share/icons/hicolor/256x256/apps/appimagekit_3cac35213efbe4940e6536e23f10ff3b_go_flutter_test.png"
Segmentation fault (core dumped)
```

**Comment by probonopd** [comment] 2020-05-02 12:40
I'm happy to look into this but please do open issues in the respective projects (the ones that crash) so that we don't mix up different things.

**Comment by jld3103** [comment] 2020-05-02 12:41
I'm not sure if appimagelauncher and appimaged are the problems. Maybe it's just my wrong packaging?

**Comment by jld3103** [comment] 2020-05-02 12:48
Ok I'm getting some error logs. I'll try to fix them and hope that it works then. Let's see

**Comment by jld3103** [comment] 2020-05-02 12:49
But odd that the go-appimagetool reports misconfiguration while the normal appimagetool doesn't.

**Comment by jld3103** [comment] 2020-05-02 12:56
Still the same. No clue what to do now.

**Comment by probonopd** [comment] 2020-05-02 13:46
If you can write something down that I can reproduce I'll gladly help. (Especially since I am essentially moving everything to Go right now.)

**Comment by jld3103** [comment] 2020-05-02 13:54
I'll try

**Comment by jld3103** [comment] 2020-05-06 21:56
@probonopd With that PR the tool generates the attached folder and the packages it. After copying the AppImage to `~/Applications` and I run `appimaged` and get this error:
```log
appimaged, continuous build (commit b096cd3), build 221 built on 2020-03-30 19:16:46 UTC
Watching /home/jld3103/.local/bin
Watching /home/jld3103/Downloads
Watching /home/jld3103/bin
Extracting usr/share/icons/hicolor/256x256/apps/go_flutter_test.png to "/home/jld3103/.local/share/icons/hicolor/256x256/apps/appimagekit_0119f5b16156d92850d361fa897d0634_go_flutter_test.png"
Segmentation fault (core dumped)
```
Can you reproduce it?
This is no information about the error, but I hope you can confirm that there is an error.
[hover-build-go_flutter_test-linux-appimage928923469.tar.gz](https://github.com/go-flutter-desktop/go-flutter/files/4589638/hover-build-go_flutter_test-linux-appimage928923469.tar.gz)

**Comment by jld3103** [comment] 2020-05-06 21:57
@marchellodev Can you try https://github.com/go-flutter-desktop/hover/pull/115 and submit the AppImage to try if the check still fails? (You have to clone the branch and do a `go install`. To go back just follow the install steps again)

**Comment by marchellodev** [comment] 2020-05-07 12:21
@jld3103
https://travis-ci.org/github/AppImage/appimage.github.io/builds/684236478

**Comment by jld3103** [comment] 2020-05-07 13:00
I think is not the fault of go-flutter or hover.
`./build/sharik: /lib/x86_64-linux-gnu/libm.so.6: version 'GLIBC_2.27' not found (required by ./build/sharik)` indicates that there is something wrong with the glibc version

**Comment by probonopd** [comment] 2020-05-07 17:51
> @probonopd With that PR the tool generates the attached folder and the packages it. After copying the AppImage to ~/Applications and I run appimaged and get this error:

From the message above, it looks like you are running into an issue in

```
appimaged, continuous build (commit b096cd3), build 221 built on 2020-03-30 19:16:46 UTC
```

Please report over at https://github.com/AppImage/appimaged/issues.

**Comment by marchellodev** [comment] 2020-05-09 12:57
This was built on Ubuntu 16.04 with @jld3103's pull request https://travis-ci.org/github/AppImage/appimage.github.io/builds/685028088

**Comment by marchellodev** [comment] 2020-05-09 12:59
When trying to run it: `Segmentation fault` and that's it

**Comment by jld3103** [comment] 2020-05-09 13:48
That error is completely different from what this issue is about.
Can we close this when https://github.com/go-flutter-desktop/hover/pull/115 is merged and you open a new issue?

**Comment by marchellodev** [comment] 2020-05-09 14:03
Ok, that's fine

**Comment by jld3103** [comment] 2020-05-11 17:59
Merged in https://github.com/go-flutter-desktop/hover/commit/b9d881be5eae011d61e3d6d2ed1e2830a9267b1f
It is not published yet, because there are going to be some changes, but if you want the fixed version you can clone the hover repo and do a `go install`.
I will closes this issue, because the original error is fixed.

**Closed by jld3103** 2020-05-11 17:59 UTC
Labels: bug, hover

**Comment by GeertJohan** [comment] 2020-05-13 09:02
If you do a `go install`, be sure to also locally create the docker image if you'd like to use --docker.

The easiest way to do that is to read and run `install-with-docker-image.sh` in the root of the repo.
