### ISSUE TITLE
I want to use WebView

### ISSUE THREAD

**Issue by chuguofei** [go-flutter-desktop/go-flutter#476] opened 2020-06-16 03:40 UTC
Trying to use the default webview implemntation for  TargetPlatform.fuchsia but there isn't a defatult one , What should I am going to do?

**Comment by qianniancn** [comment] 2020-06-16 09:10
你需要写插件

**Comment by pchampio** [comment] 2020-06-16 09:23
Duplicate of: #324 
TL;DR: we don't plan to implement the webview plugin.

**Closed by pchampio** 2020-06-16 09:23 UTC
Labels: enhancement
