### ISSUE TITLE
embedder_surface_gl Error

### ISSUE THREAD

**Issue by alexelisenko** [go-flutter-desktop/go-flutter#172] opened 2019-06-28 15:24 UTC
I am getting the following error:

```
[ERROR:flutter/shell/platform/embedder/embedder_surface_gl.cc(89)] Could not create a resource context for async texture uploads. Expect degraded performance. Set a valid make_resource_current callback on FlutterOpenGLRendererConfig.
```

```
Flutter 1.7.10-pre.19 • channel master • https://github.com/flutter/flutter.git
Framework • revision 305a99501e (3 days ago) • 2019-06-25 18:20:39 -0400
Engine • revision 107fe82343
Tools • Dart 2.4.0
```
I see that this might have been resolved in: #68 , but not sure on how to debug this. Any help would be appreciated.

**Comment by Drakirus** [comment] 2019-06-28 19:45
This error isn't critical, it doesn't have any effect on go-flutter-desktop.

Closing since it's a duplicate of #82

**Closed by Drakirus** 2019-06-28 19:45 UTC

**Comment by alexelisenko** [comment] 2019-06-28 21:27
@Drakirus I probably should have added more details. I dont know if that error is related to my issue, but, on Mac OS 10.14.5, when I build with flutter, the UI is very responsive and I never have any missed mouse clicks, but when I use go-flutter, the UI misses mouse clicks almost 20-30% of the time.

Since that error mentioned performance, I thought it may be related, if it not, then are there any build differences between flutter and go-flutter that would cause this?

**Comment by GeertJohan** [comment] 2019-07-02 15:59
I don't think it's related, but this is indeed an issue I have been noticing recently. Likely a regression we recently made. I'll be opening a new issue for this problem
