### ISSUE TITLE
Use github actions to release

### ISSUE THREAD

**Issue by CaiJingLong** [go-flutter-desktop/go-flutter#315] opened 2019-11-19 01:17 UTC
I want to use github actions to build macOS application.
I'm using the image of macOS-10.14 provided by github actions, but it seems have problem.

https://github.com/CaiJingLong/JsonToDart/releases/tag/v0.0.20

I get the result when I double click to open it.
![image](https://user-images.githubusercontent.com/14145407/69026684-d9e58280-0a06-11ea-83b6-d0236137e7c8.png)

---

And if I use the cli to open the binary of flutter, it is normal.
`$JsonToDart.app/Contents/MacOS/json_to_dart` 

After opening via cli, the app is also restored to normal, I can open it by double-clicking.

Zip file is my screen recorder to reproducing the problem.
[Kapture 2019-11-18 at 13.31.14.mp4.zip](https://github.com/go-flutter-desktop/go-flutter/files/3856912/Kapture.2019-11-18.at.13.31.14.mp4.zip)

---

hover doctor

```bash
hover doctor
hover: Running on darwin
hover: Docker installed: true
hover: Sharing flutter version
Flutter 1.9.1+hotfix.4 • channel beta • https://github.com/flutter/flutter.git
Framework • revision cc949a8e8b (7 weeks ago) • 2019-09-27 15:04:59 -0700
Engine • revision b863200c37
Tools • Dart 2.5.0
hover: Flutter engine commit: https://github.com/flutter/engine/commit/b863200c37
hover: Finding out the C compiler version
Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin19.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
hover: Sharing the content of go.mod
module github.com/fluttercandies/JsonToDart/tree/master/Flutter/desktop/desktop

go 1.12

require (
        github.com/go-flutter-desktop/go-flutter v0.33.0
        github.com/pkg/errors v0.8.1
        github.com/stretchr/objx v0.2.0 // indirect
        gopkg.in/check.v1 v1.0.0-20190902080502-41f04d3bba15 // indirect
        gopkg.in/yaml.v2 v2.2.5 // indirect
)
hover: Warning: No hover.yaml file found: open go/hover.yaml: no such file or directory
hover: Sharing the content of go/cmd
go/cmd/compatibility_darwin.go  go/cmd/main.go  go/cmd/options.go
```

**Comment by pchampio** [comment] 2019-11-19 09:30
Duplicate of #313 
Sorry for making you create another issue, I didn't realize it was the cause of 313.

**Comment by pchampio** [comment] 2019-12-04 10:11
Without additional information, we are unfortunately not sure how to resolve
this issue. Please follow #310 as the issue has more comments.

Thanks for your contribution.

**Closed by pchampio** 2019-12-04 10:11 UTC
Labels: needs info
