### ISSUE TITLE
To package linux-pkg these tools are required: makepkg (with Docker)

### ISSUE THREAD

**Issue by marchellodev** [go-flutter-desktop/go-flutter#485] opened 2020-06-30 13:04 UTC
When running `hover build linux-pkg --docker`:

```
hover: Compiling go binary using docker container
Running this docker command: /usr/bin/docker run --rm --mount type=bind,source=/home/marchello/Desktop/sharik/sharik,target=/app --mount type=bind,source=/home/marchello/.cache/hover/engine,target=/root/.cache/hover/engine --mount type=bind,source=/home/marchello/.cache/hover/docker-go-cache,target=/go-cache --env GOCACHE=/go-cache --env HOVER_SAFE_CHOWN_UID=1001 --env HOVER_SAFE_CHOWN_GID=1001 --env GOPROXY=https://proxy.golang.org,direct
 --env GOPRIVATE=
 goflutter/hover:v0.42.0 hover-safe.sh build linux-pkg --skip-flutter-build-bundle --skip-engine-download
docker container: hover: To package linux-pkg these tools are required: makepkg
docker container: hover: To still package linux-pkg without the required tools installed you need to run hover with the `--docker` flag.
hover: Docker run failed: exit status 1
```

**Comment by jld3103** [comment] 2020-06-30 13:55
The problem is known. I haven't found a solution yet, but PRs are welcome. I already tried copying from an arch stage and building it on ubuntu, but it wouldn't work because of some library incompatabilities. I can post the code for building on ubuntu later so anyone can tinker with it.

**Comment by jld3103** [comment] 2020-09-05 11:23
It's fixed with this PR: https://github.com/go-flutter-desktop/hover/pull/164

**Closed** 2020-11-01 19:58 UTC
