### ISSUE TITLE
 Failed to find hover assets

### ISSUE THREAD

**Issue by axilesoft** [go-flutter-desktop/go-flutter#257] opened 2019-09-10 05:29 UTC
Error, After installing hover with `go get -u github.com/go-flutter-desktop/hover` (on Windows 10)
`
>hover
hover: Failed to find hover assets: could not locate box "../assets"
`

**Comment by Drakirus** [comment] 2019-09-11 10:28
also happens to me when I remove the path on which hover was installed:
```sh
/tmp
$ git clone https://github.com/go-flutter-desktop/hover.git
Clonage dans 'hover'...
remote: Enumerating objects: 24, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 475 (delta 11), reused 16 (delta 9), pack-reused 451
Réception d'objets: 100% (475/475), 151.07 Kio | 568.00 Kio/s, fait.
Résolution des deltas: 100% (258/258), fait.

/tmp
$ cd hover
assets  cmd  go.mod  go.sum  internal  LICENSE  main.go  README.md  renovate.json

/tmp/hover master
$ go install

/tmp/hover master
$ hover help
Hover helps developers to release Flutter applications on desktop.

Usage:
  hover [flags]
  hover [command]

Available Commands:
  build          Build a desktop release
  help           Help about any command
  init           Initialize a flutter project to use go-flutter
  init-packaging Create configuration files for a packaging format
  run            Build and start a desktop release, with hot-reload support
  upgrade        upgrade the 'go-flutter' core library

Flags:
  -h, --help   help for hover

Use "hover [command] --help" for more information about a command.

/tmp/hover master
$ cd ..

/tmp
$ rm hover

/tmp
$ hover help
hover: Failed to find hover assets: could not locate box "../assets"

``` 

can you manually clone hover in something like `C:\app\hover` and run `go install` in that directory to check if hover works

**Comment by axilesoft** [comment] 2019-09-11 11:56
It works when install from the clone source directory.

**Comment by Drakirus** [comment] 2019-09-11 12:02
I don't know why `go get -u github.com/go-flutter-desktop/hover` isn't working in your system.

Could you share your `$GOPATH`? @GeertJohan is the author of [go.rice](https://github.com/GeertJohan/go.rice) he might have ideas why it's not working.

As the issue is more related to your system and go.rice, closing the issue for now.
This can be reopen if multiples users gets the same behavior as you.

**Comment by axilesoft** [comment] 2019-09-11 12:31
I'm new to Go language.  I'm testing go-flutter on Windows 10.
I just follow the instruction:
1) install Go  with the msi installer.
2) open the Flutter Cconsole 
3) go get -u github.com/go-flutter-desktop/hover

**Comment by GeertJohan** [comment] 2019-09-11 14:59
Hmm. Maybe recent versions of Go clone the package in a tmp dir, which means the sourcecode and assets are removed after a while. I will investigate.

**Comment by jld3103** [comment] 2019-09-17 12:48
I got that same issue, when I mounted the app code into a Docker container.

**Comment by Drakirus** [comment] 2019-10-20 21:46
Go doesn't clone package to a tmp dir, I think this error was caused to some Golang configuration problem (GOPATH wrongly set).

I want to keep the backlog as clean as possible, closing this issue.

**Closed by Drakirus** 2019-10-20 21:46 UTC
Labels: has-workarround, hover, needs info
