### ISSUE TITLE
hover run failing to run on MacOs

### ISSUE THREAD

**Issue by erickzanardo** [go-flutter-desktop/go-flutter#255] opened 2019-09-08 16:51 UTC
## Flutter version

```
Flutter 1.7.8+hotfix.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 20e59316b8 (7 weeks ago) • 2019-07-18 20:04:33 -0700
Engine • revision fee001c93f
Tools • Dart 2.4.0
```

I have been using go-flutter on my project with success for quite some time, but right now for some reason `hover run` is failing to execute with the following log:

```
Downloading engine for platform darwin-x64 at version fee001c93f...
Download completed in 2.923052435s
Downloading artifacts at version fee001c93f...
Download completed in 5.619980669s
Running "flutter pub get" in tales...                               0.7s
go: finding github.com/go-flutter-desktop/go-flutter master
go: finding github.com/go-gl/gl latest
go: finding github.com/go-gl/glfw latest
go: finding gopkg.in/check.v1 latest
# github.com/go-flutter-desktop/go-flutter/embedder
Undefined symbols for architecture x86_64:
  "_FlutterPlatformMessageCreateResponseHandle", referenced from:
      _createMessageResponseHandle in _x005.o
  "_FlutterPlatformMessageReleaseResponseHandle", referenced from:
      __cgo_84ad20d147fe_Cfunc_FlutterPlatformMessageReleaseResponseHandle in _x003.o
     (maybe you meant: __cgo_84ad20d147fe_Cfunc_FlutterPlatformMessageReleaseResponseHandle)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Go get -u github.com/go-flutter-desktop/go-flutter failed: exit status 2
```

That was happening on Flutter 1.7.8+hotfix.3, I tried upgrading Flutter to see if that would fiz, but the error persisted.

Is this a bug on `go-flutter`? Or something wrong with my project?

Thanks

**Comment by Drakirus** [comment] 2019-09-08 17:00
The go-flutter project tries to stay compatible with the beta channel of Flutter.

Please update the flutter channel to the latest beta version.

**Comment by Drakirus** [comment] 2019-09-08 17:01
Duplicate of #246

**Closed by Drakirus** 2019-09-08 17:00 UTC

**Comment by erickzanardo** [comment] 2019-09-08 17:04
I changed to the beta channel, it is working fine now, I am gonna keep that in mind for the future. Thanks for the quick response.

**Comment by Drakirus** [comment] 2019-09-08 17:09
I can also see that your hover version is quite old.
You definitely should update hover: `go get -u github.com/go-flutter-desktop/hover`
