### ISSUE TITLE
fatal error: 'windows.h' file not found

### ISSUE THREAD

**Issue by DJafari** [go-flutter-desktop/go-flutter#470] opened 2020-06-12 00:15 UTC
## Hover doctor

```
hover: Hover version v0.42.0 running on darwin
hover: Sharing flutter version
Flutter 1.20.0-1.0.pre.21 • channel master •
https://github.com/flutter/flutter.git
Framework • revision d25b9c80a4 (8 hours ago) • 2020-06-11 09:31:05 -0700
Engine • revision 965fbbed17
Tools • Dart 2.9.0 (build 2.9.0-14.0.dev 2b917f5b6a)
hover: Flutter engine commit: https://github.com/flutter/engine/commit/965fbbed1776545ee681cb57f3fb1d0c2000bbcb
hover: ⚠ The go-flutter project tries to stay compatible with the beta channel of Flutter.
hover: ⚠     It's advised to use the beta channel: `flutter channel beta`
hover: Finding out the C compiler version
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin19.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
hover: Sharing the content of go.mod
module github.com/go-flutter-desktop/examples/stocks/go

go 1.14

require (
	github.com/go-flutter-desktop/go-flutter v0.41.1
	github.com/pkg/errors v0.9.1
)
hover: Sharing the content of hover.yaml
application-name: ""
executable-name: ""
package-name: ""
license: ""
target: lib/main_desktop.dart
branch: ""
cache-path: ""
opengl: ""
engine-version: ""
hover: Sharing the content of go/cmd
go/cmd/main.go	go/cmd/options.go
```

## Error output

Using `hover build windows` to build my application, I get the following
error:

```log
hover: Cleaning the build directory
hover: ⚠ The go-flutter project tries to stay compatible with the beta channel of Flutter.
hover: ⚠     It's advised to use the beta channel: `flutter channel beta`
hover: Building flutter bundle
Font subetting is not supported in debug mode. The --tree-shake-icons flag will
be ignored.
hover: Missing/Empty `version` field in pubspec.yaml. Please add it or otherwise you may publish your app with a wrong version. Continuing with `0.0.1` as a placeholder version.
hover: Using engine from cache
hover: Compiling 'go-flutter' and plugins
runtime/cgo
# runtime/cgo
gcc_libinit_windows.c:7:10: fatal error: 'windows.h' file not found
hover: Go build failed: exit status 2
```

**Comment by pchampio** [comment] 2020-06-14 20:16
` gcc-mingw-w64 ` isn't installed on your machine.
You can either install it or use the `--docker` flag.

Duplicate of: https://github.com/go-flutter-desktop/go-flutter/issues/411

**Closed by pchampio** 2020-06-14 20:16 UTC
Labels: duplicate

**Comment by DJafari** [comment] 2020-06-14 21:14
@pchampio 
but i have mingw-w64 in my mc

```
$ brew install mingw-w64

Warning: mingw-w64 7.0.0._2 is already installed and up-to-date
```

how can i build it with `--docker` flag ?
