### ISSUE TITLE
hover cannot get hover / assets / app / directory

### ISSUE THREAD

**Issue by qianniancn** [go-flutter-desktop/go-flutter#401] opened 2020-04-20 10:29 UTC
## Can't get “app ” directory
```
$ go get -u github.com/go-flutter-desktop/hover
```
The `hover init` command will cause the main.go file not to be found

## Screenshot
![2020-04-20 182902](https://user-images.githubusercontent.com/5478237/79742203-0e9e9280-8335-11ea-97b9-630a4cacd402.png)

![2020-04-20 183854](https://user-images.githubusercontent.com/5478237/79742952-3fcb9280-8336-11ea-8e00-15aec56047fb.png)

**Comment by pchampio** [comment] 2020-04-20 11:00
What is the output of `go env` ?

**Comment by qianniancn** [comment] 2020-04-20 11:01
> 输出是`go env`什么？
````
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\bxe\AppData\Local\go-build
set GOENV=C:\Users\bxe\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\bxe\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=D:\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\bxe\AppData\Local\Temp\go-build775257918=/tmp/go-build -gno-record-gcc-switches
````

**Comment by qianniancn** [comment] 2020-04-20 11:04
Can't it be set to `GO111MODULE=on` ？

**Comment by GeertJohan** [comment] 2020-04-20 11:10
It should be on, yes. We depend on Go-module based building in new features. But I forgot it would break our assets embedding. Working on a fix right now at go-flutter-desktop/hover#101.

**Comment by pchampio** [comment] 2020-04-20 11:11
duplicate of: https://github.com/go-flutter-desktop/go-flutter/issues/306 we are working on a fix: https://github.com/go-flutter-desktop/hover/pull/101

> Can't it be set to GO111MODULE=on

It seems that only `auto` works.

**Closed by pchampio** 2020-04-20 11:11 UTC
Labels: duplicate

**Comment by GeertJohan** [comment] 2020-04-20 12:32
@qianniancn Can you please try with the latest version of hover?
```bash
GO111MODULE=on go get -u -a github.com/go-flutter-desktop/hover@v0.40.2
```

It should work (it may error on the folder `go` already existing in your flutter project, if you have not done any work to the `go` folder you can remove it from the project and let `hover init` create it again.

**Comment by qianniancn** [comment] 2020-04-20 12:42
> @qianniancn Can you please try with the latest version of hover?
> 
> ```shell
> GO111MODULE=on go get -u -a github.com/go-flutter-desktop/hover@v0.40.2
> ```
> 
> It should work (it may error on the folder `go` already existing in your flutter project, if you have not done any work to the `go` folder you can remove it from the project and let `hover init` create it again.

can use `GO111MODULE=o`n, which is a perfect solution, thank you!
![2020-04-20 204158](https://user-images.githubusercontent.com/5478237/79752824-79f16000-8347-11ea-82bf-2d6e4b0eef14.png)
![2020-04-20 204225](https://user-images.githubusercontent.com/5478237/79752832-7bbb2380-8347-11ea-869e-b7c0e7005be5.png)
