### ISSUE TITLE
Copy paste (android way) crashes the app

### ISSUE THREAD

**Issue by mikesies** [go-flutter-desktop/go-flutter#98] opened 2019-03-25 09:51 UTC
## Flutter version

Flutter 1.3.9 • channel dev • https://github.com/flutter/flutter.git
Framework • revision f91df4abe1 (2 weeks ago) • 2019-03-09 21:19:28 -0500
Engine • revision 4e54bc93ca
Tools • Dart 2.2.1 (build 2.2.1-dev.1.0 2fb6cd9f5f)

## Steps to Reproduce

When I double click on a TextFormField and click Paste on the popup that appears, the application crashes. Pasting using CTRL+V does work. Using Ubuntu 18.4.2

**Comment by GeertJohan** [comment] 2019-03-25 19:50
This is caused by the synchronous handling of platform messages. I'm still waiting on https://github.com/flutter/flutter/issues/29444

**Comment by GeertJohan** [comment] 2019-03-28 15:35
Fixed by 676de77352dbd7b24ea18e16607e67a87b1a5b0e

**Closed by GeertJohan** 2019-03-28 15:35 UTC
Labels: bug
