### ISSUE TITLE
Windows execute file is not executed in chinese file path or directory

### ISSUE THREAD

**Issue by tsungyumr** [go-flutter-desktop/go-flutter#341] opened 2020-01-14 03:38 UTC
Hello, thanks for great project to help building desktop application using flutter,
There is problem when hover build windows completed, I find program file in the project directory
....\go\build\output\windows\xxxx.exe
When I change directory name from windows to chinese charactors name, the program xxxx.exe is not running when you click it,back to english directory name,it works again,It is also happend when there are chinese charactors path name,like c:\測試\windows\xxxx.exe.
I don't know why? Please help me to check out what is going wrong.

**Comment by pchampio** [comment] 2020-01-15 00:24
I don't have any issue on linux.
Could you share error (the one outputed by the terminal)?
What command are you using?
Hover build ...
Hover run...
Thanks for your contribution.

**Comment by tsungyumr** [comment] 2020-01-15 00:48
As I metioned before,I used "hover build windows" to build windows application,I have no idea hover build on linux or mac os,and next step,trying to change directory name from English name "windows" to Chinese name likes "測試",and then double click program file inside directory,application is not running,when change back to English name "windows",application works again.There is no special error when doing command "hover build windows".

**Comment by pchampio** [comment] 2020-01-15 08:22
Thanks,
Can you change your folder to a Chinese one and start the application using 'hover run'?
This way we will get a error in the terminal.

**Comment by tsungyumr** [comment] 2020-01-15 08:57
Ok, It is good idea, I have follow what you said,and got error reported on command screen.
λ hover run
hover: Using engine from cache
hover: Cleaning the build directory
hover: Bundling flutter app
hover: Checking available release on Github
hover: The core library 'go-flutter' has an update available. (v0.30.0 -> 0.34.1)
hover:               To update 'go-flutter' in this project run: $ hover upgrade
hover: Failed to retrieve the organization name: open android/app/src/main/AndroidManifest.xml: The system cannot find the path specified.
hover: Compiling 'go-flutter' and plugins
iyoyo_downloader/go/cmd
hover: Successfully compiled
hover: Build finished, starting app...
hover: Running downloader in debug mode
embedder.cc (674): 'FlutterEngineInitialize' returned 'kInvalidArguments'. Not running in AOT mode but could not resolve the kernel binary.go-flutter: engine.Run() returned result code 2 (invalid arguments)

hover: App 'downloader' exited with error: exit status 1

**Comment by pchampio** [comment] 2020-01-15 09:42
Either [this (go-flutter)](https://github.com/go-flutter-desktop/go-flutter/blob/ef6b553dadcace83ce35a0651ea0cbeb3b2a08af/application.go#L169-L186) code or [this (engine)](https://github.com/flutter/engine/blob/46adf73d5128269ed75572368eb720117d771ca8/shell/platform/embedder/embedder.cc#L669-L680) isn't doing something correctly.

**Comment by Tokenyet** [comment] 2020-01-23 15:53
Hi @pchampio ! Is there any issue on flutter/flutter ? I just want to leave a subscribe for good news 😄

Overall, notice users to change to English path is the workaround in this situation, am I right 😕 ?

**Comment by pchampio** [comment] 2020-01-23 16:21
> Overall, notice users to change to English path is the only workaround in this situation, am I right confused ?

Yes, as I cannot reproduce this issue on linux, I don't plan on working on this, sorry.

> Hi @pchampio ! Is there any issue on flutter/flutter? I just want to leave a subscribe for good news.

As I don't want to create unnecessary issue, I haven't create an issue on their bug tracker.

**Comment by stuartmorgan** [comment] 2020-01-31 00:22
This is very likely fixed now.

**Comment by pchampio** [comment] 2020-01-31 09:12
Awesome, Thanks!

**Closed by pchampio** 2020-01-31 09:12 UTC
Labels: Windows, bug
