### ISSUE TITLE
Copy paste. Value is inserted twice.

### ISSUE THREAD

**Issue by Frank-von-Schrenk** [go-flutter-desktop/go-flutter#349] opened 2020-01-31 15:55 UTC
I try the Copy paste under Windows. Every value will be written twice.
I try it from (Chrome & Notepad) <= Same

![image](https://user-images.githubusercontent.com/51343921/73553567-75a15f00-444a-11ea-85d5-017ac0ec979f.png)

**Comment by pchampio** [comment] 2020-01-31 17:07
duplicate of https://github.com/go-flutter-desktop/go-flutter/issues/314 and https://github.com/go-flutter-desktop/go-flutter/issues/320.
I'm working on a fix https://github.com/go-flutter-desktop/go-flutter/pull/338(it will take some time to be merge, I'm busy with life atm)
As a workaround, you can use my WIP PR: `hover run -b '@fix_keyboard_shortcut' `.

**Comment by pchampio** [comment] 2020-01-31 17:08
I've pushed a hotfix https://github.com/go-flutter-desktop/go-flutter/releases/tag/v0.35.1

**Closed by pchampio** 2020-01-31 17:07 UTC

**Comment by pchampio** [comment] 2020-01-31 17:09
Please read https://github.com/go-flutter-desktop/go-flutter/issues/319#issuecomment-558557949

**Comment by Tokenyet** [comment] 2020-02-08 18:04
Thanks for the fix! It works now!
