### ISSUE TITLE
Way to avoid cmd when launching application on Windows

### ISSUE THREAD

**Issue by radzish** [go-flutter-desktop/go-flutter#135] opened 2019-05-14 20:33 UTC
Is that possible. If so, how it can be done. disclaimer: I am not go expert

**Comment by Drakirus** [comment] 2019-05-14 21:00
Yes it is possible #61.
But hover doesn't implement the feature yet #106, [hover code to modify](https://github.com/go-flutter-desktop/hover/blob/b9fe41062a92cfd52a6098ad2be81e1a7cfef0ed/cmd/build.go#L180-L184). 
By using the manual compilation method [wiki](https://github.com/go-flutter-desktop/go-flutter/wiki), you can pass the flag to `go build`.

Closing since it's a duplicate of: #106

**Closed by Drakirus** 2019-05-14 21:00 UTC
