### ISSUE TITLE
Multi-window support

### ISSUE THREAD

**Issue by rs5173** [go-flutter-desktop/go-flutter#385] opened 2020-04-05 09:45 UTC
My application has a requirement, a new window pops up anywhere on the desktop, does it support this function？

**Comment by pchampio** [comment] 2020-04-05 09:50
No sorry we don't have multiple window support yet.
Duplicate of https://github.com/go-flutter-desktop/go-flutter/issues/123

**Closed by pchampio** 2020-04-05 09:50 UTC
Labels: enhancement
