### ISSUE TITLE
[Question] How can I build an x86 exe to run on the x86 devices?

### ISSUE THREAD

**Issue by ResetPower** [go-flutter-desktop/go-flutter#227] opened 2019-08-07 03:10 UTC
Hi! I am a Chinese, I can't speak English very well.
I want to build an x86 exe to run on the x86 devices. I develop on macOS, I create a Windows x64 virtual machine to develop and test the Windows editions. But some user uses x86 devices. What should I do?

**Comment by Drakirus** [comment] 2019-08-07 09:11
duplicate of #127 #161 # 195

**Closed by Drakirus** 2019-08-07 09:11 UTC
