### ISSUE TITLE
I can't use the backspace key to delete text on a textfield from the end.

### ISSUE THREAD

**Issue by ContainsK** [go-flutter-desktop/go-flutter#354] opened 2020-02-16 08:14 UTC
I can't use the backspace key to delete text on a textfield from the end.
But we can use the Del key, which is not consistent with our habits.

**Comment by pchampio** [comment] 2020-02-17 10:43
Duplicate of https://github.com/go-flutter-desktop/go-flutter/issues/314

Please read https://github.com/go-flutter-desktop/go-flutter/issues/319#issuecomment-558557949

**Closed by pchampio** 2020-02-17 10:43 UTC
