### ISSUE TITLE
windows-msi: /usr/bin/ld: cannot find -lflutter_engine

### ISSUE THREAD

**Issue by marchellodev** [go-flutter-desktop/go-flutter#413] opened 2020-04-26 13:53 UTC
Command: `hover build windows-msi --docker`

Response:
```
...
docker container: # github.com/go-flutter-desktop/go-flutter/embedder
docker container: /usr/bin/ld: cannot find -lflutter_engine
docker container: collect2: error: ld returned 1 exit status
docker container: hover: Updating go-flutter to @latest version failed: exit status 2
hover: Docker run failed: exit status 1
```

**Comment by marchellodev** [comment] 2020-04-26 13:59
Weird, now it works
Probably due to some connectivity issues

**Comment by jld3103** [comment] 2020-04-26 14:06
This problem is known and cannot be fixed. Rerunning fixes it

**Comment by GeertJohan** [comment] 2020-04-28 07:30
How does this problem occur? Indeed due to connectivity issues, would that be in the logs? Or is it always the case that windows-msi must be run twice before it works?

**Comment by jld3103** [comment] 2020-04-28 10:51
Just because the `go/build/outputs/windows` folder in this case doesn't exist and the flutter engine isn't copied before that step it seems

**Comment by jld3103** [comment] 2020-04-28 10:52
I think it only happens in docker

**Comment by jld3103** [comment] 2020-05-06 22:02
@marchellodev Can you describe the exact setup you have, because I was unable to reproduce the error, but I know it exist, because I got also got it sometimes a few months ago.

**Comment by james-lawrence** [comment] 2020-05-07 22:50
this looks like the issue i've been running into. it has to do with the engine cache path and the go get download.

**Comment by bzsome** [comment] 2020-05-08 04:47
I had the same problem,mingw32/bin/ld.exe: cannot find -lflutter_engine

<img src="https://user-images.githubusercontent.com/35402969/81371215-da471680-9129-11ea-94fe-a2a94fd26063.jpg">

**Comment by GeertJohan** [comment] 2020-05-09 13:48
This can happen when there are special characters such as spaces(` `) or dashes(`-`) in the path to the flutter engine. The path is passed to the Linker via the CGO_LDFLAGS env, but needs better escaping to handle spaces and dashes.

**Comment by pchampio** [comment] 2020-05-25 15:56
@bzsome your issue is because your ran go build main.go. (cf the screen on the tag)
Please use https://github.com/go-flutter-desktop/hover.

**Comment by pchampio** [comment] 2020-05-25 16:21
@marchellodev  the issue comes because.
Hover hasn't cached the linux engine. (and it shouldn't since you want to build for windows)
Hover is used with the `-b` or `hover.yaml` `branch` branch flag set.
Hover tries to `go get` go-flutter (the behavior when `-b` or `branch` in hover.yaml is used)
Hover when `go get` -ing cache compile go-flutter but fail because the windows lib was cached and not the linux one.

How to reproduce (on linux):
```
$ rm ~/.config/hover/engine/*
$ hover build windows-msi --docker -b '@master'
```

How to fix: tell go get to stop cache compiling sutff with the go get `-d` flag. https://github.com/go-flutter-desktop/hover/pull/142

**Comment by pchampio** [comment] 2020-05-30 18:31
Closed by: https://github.com/go-flutter-desktop/hover/pull/142
please update hover to v0.42.0

**Closed by pchampio** 2020-05-30 18:31 UTC
Labels: bug, hover
