### ISSUE TITLE
Drag the windows size with the mouse a few times lead the application crash in my mac os

### ISSUE THREAD

**Issue by jstyarsenal** [go-flutter-desktop/go-flutter#325] opened 2019-12-23 08:26 UTC
I try to compile the examples/flutter_gallery in my mac os with flutter beta channel with command "flutter build macos" and hover command "hover build darwin-bundle". Both of these methods can compile successfully. But when I double click the darwin-bundle flutter_gallery with mouse and drag the application window size especially from top line to bottom line direction, it always crash. But I run the flutter build macos and drag the window size,I have never meet the crash problem

**Comment by pchampio** [comment] 2019-12-23 08:53
duplicate of https://github.com/go-flutter-desktop/go-flutter/issues/133
a fix is coming soon https://github.com/go-flutter-desktop/go-flutter/pull/308

**Comment by pchampio** [comment] 2019-12-23 08:54
Do you encounter this bug with: `hover run -b '@no_resize_crash'` ?

**Closed by pchampio** 2019-12-23 08:53 UTC
